### ISSUE TITLE
fetch google benchmark via cmake

### ISSUE THREAD

**Issue by HDembinski** [boostorg/histogram#163]
B. Reese: "Btw, if you want cmake to fetch google benchmark for you (think of it as a lazy-loaded git submodule) then I have written a script for that: https://github.com/breese/trial.online/tree/develop/benchmark"

**Comment by henryiii** [comment]
Here's a similar set of examples for GoogleTest:

https://cliutils.gitlab.io/modern-cmake/chapters/testing/googletest.html

**Comment by HDembinski** [comment]
implemented on develop
