### ISSUE TITLE
Support for integer shrink

### ISSUE THREAD

**Issue by henryiii** [boostorg/histogram#183]
I would like to have a version of the shrink option where I can set an upper or lower limit (or both) with a bin number instead of a coordinate. Ideally this could even work on all axis types, but not critical.

**Comment by HDembinski** [comment]
It makes sense to support this in Python, because it already has slicing, but I am not sure how many people actually want to slice on indices.

**Comment by HDembinski** [comment]
To implement this as part of the `reduce` function, I need a new "keyword". I already have `rebin`, `shrink` and `shrink_and_rebin`. What about `slice` and `slide_and_rebin`?

**Comment by HDembinski** [comment]
@jpivarski Any thoughts on names?

**Comment by jpivarski** [comment]
It seems to me that `slice` is the appropriate name for this. `shrink` is unfamiliar to me, but I remember that conversation: it's an STL standard.

**Comment by HDembinski** [comment]
implemented in develop
