### ISSUE TITLE
Support BOOST_NO_EXCEPTIONS

### ISSUE THREAD

**Issue by glenfe** [boostorg/histogram#189]
The library does this well in most places, but two still use `try`, `catch`, `throw` directly which won't compile on those environments where exception support is disabled.

**Comment by HDembinski** [comment]
Working on it... https://github.com/HDembinski/histogram/pull/32

**Comment by glenfe** [comment]
Your tests can continue to `throw`, i.e. only the library needs to support `BOOST_NO_EXCEPTIONS` (tests that test exceptions should test exceptions, to be able to do things like `BOOST_TEST_THROWS`).

In general I avoid `try`, `catch`, re-`throw` and RAII instead, since that works equally in exceptions mode and without exceptions: https://github.com/boostorg/histogram/pull/190

The PR also switches to `boost::alloc_construct_n` and `boost::alloc_destroy_n` from Boost.Core.

**Comment by HDembinski** [comment]
I didn't see your PR in time, which is of course much nicer than my solution. You said I can throw/catch in the tests, but I also want to test the "-fno-exceptions -fno-rtti" support, and then I can't throw/catch in the tests either. I will try to merge the two.

**Comment by glenfe** [comment]
> You said I can throw/catch in the tests, but I also want to test the "-fno-exceptions -fno-rtti" support, and then I can't throw/catch in the tests either. 

*Nod*, if you want to test the -fno-exceptions support, then you can't throw in the tests that test it.

Just make sure you don't sacrifice any existing testing you have of exceptions support. e.g. If you have tests that check that an exception was correctly thrown via `BOOST_TEST_THROWS()`, those tests are valuable too.

**Comment by glenfe** [comment]
> I will try to merge the two.

#190 updated (should merge cleanly).

**Comment by HDembinski** [comment]
> If you have tests that check that an exception was correctly thrown via BOOST_TEST_THROWS(), those tests are valuable too.

Sure, I just put ifdefs around those. I want to keep 100 % line coverage and that means I have to test various exception paths as well.

**Comment by HDembinski** [comment]
Thank you again for this nice patch. I am aware of the RAII method, but didn't think of using it here. Very nice, I learned something.
