### ISSUE TITLE
Design Boost.Histogram logo

### ISSUE THREAD

**Issue by HDembinski** [boostorg/histogram#200]
It would be nice to have a nifty logo.

**Comment by henryiii** [comment]
Any examples of logos you like in other projects, especially boost ones?

**Comment by HDembinski** [comment]
Thanks for giving this some thought. :) 

Most Boost library don't have logos, so we are mostly unbounded. Some libraries use variations of the main boost logo that you can see https://www.boost.org/ on the top left. Some do something else entirely, see https://github.com/boostorg/beast/

I was thinking of forming the word "Histogram" out of actual histograms, showing off some of the special features of this library, like the polar axes. For most letters I would use a "3D rendering" of a 2D bar histogram, except for the "o" letter, for which I would use a polar histogram.

**Comment by HDembinski** [comment]
Proposal

![boost_histogram_logo](https://user-images.githubusercontent.com/2631586/67385268-1bfbdf80-f593-11e9-8c87-371853c3c7b2.png)

**Comment by henryiii** [comment]
The font looks a little generic/ugly to me - what about finding one like the main boost logo?

In fact, you could even make it look quite a bit like the boost logo, just changing the hexagons for the bars you have here.

**Comment by henryiii** [comment]
Cute, the outline is an H. Just noticed that, I like it :)

**Comment by HDembinski** [comment]
Boost logo resources (thanks go to the boost mailing list):
https://github.com/boostorg/website/tree/workplace/logo
https://github.com/boostorg/geometry/tree/develop/doc/other/logo

Nice summary of logos:
https://github.com/awulkiew/boost-logos

**Comment by eduardo-rodrigues** [comment]
I also like the fact that the outline of the 3 columns give the H. In that case you could use that for the H and only actually write "istogram" next to it. As for the "boost" effect you could try and have some horizontal lines to the left, as seen mildly at https://depositphotos.com/61115097/stock-illustration-healthy-lifestyle-logo-effect-paper.html and more pronouncedly at https://www.webdesign.org/photoshop/text-effects/speed-text.15189.html?

**Comment by mloskot** [comment]
If the columns were 3D hexagonal bars it would nicely correspond to the original Boost logo feature, then get some colours for the bars (like do Geometry and GIL). I may be asking for too much 😜 

![image](https://user-images.githubusercontent.com/80741/67392064-27093c80-f5a0-11e9-83d5-8063c250a9bd.png)

**Comment by vinniefalco** [comment]
![image](https://user-images.githubusercontent.com/1503976/67392349-3911bd80-f555-11e9-8ef2-82a65fa00d60.png)

**Comment by vinniefalco** [comment]
Check out the logo here https://github.com/vinniefalco/json/blob/master/README.md

**Comment by henryiii** [comment]
We could make the light blue sections of the histogram bars solid, and the dark blue sections just outlines, and that would give us a great symbol for the standardized logos seen in that sheet. A "header-bar" on the boost-histogram page would be fine, but it's not really a "logo". The boost-histogram Python logo could include the histogram bars symbol too, with different styling for the text.

**Comment by HDembinski** [comment]
@eduardo-rodrigues 
> In that case you could use that for the H and only actually write "istogram" next to it.

I will try that but I am worried it will look weird.

> As for the "boost" effect you could try and have some horizontal lines to the left, as seen mildly at https://depositphotos.com/61115097/stock-illustration-healthy-lifestyle-logo-effect-paper.html and more pronouncedly at https://www.webdesign.org/photoshop/text-effects/speed-text.15189.html?

That is a cool effect. I don't know how to generate this in inkscape, but will try. It has to be mild though, otherwise it will look tacky.

**Comment by HDembinski** [comment]
@mloskot 
> If the columns were 3D hexagonal bars it would nicely correspond to the original Boost logo feature

It would be nice to have a connection to the original Boost logo, but I don't see a way. And the Boost logo looks a bit dusty compared to modern logos. It is also not catchy at all. A logo must be catchy and memorable and appealing. The Boost logo just looks abstract.

> ![image](https://user-images.githubusercontent.com/80741/67392219-70598c00-f5a0-11e9-85fa-891d56e43f96.png)
 
> then get some colours for the bars (like do Geometry and GIL). I may be asking for too much stuck_out_tongue_winking_eye
> 
> ![image](https://user-images.githubusercontent.com/80741/67392064-27093c80-f5a0-11e9-83d5-8063c250a9bd.png)

This is nice (I also like the rainbow in principle), but I don't think anyone will notice that the shape matches with the original logo.

**Comment by HDembinski** [comment]
@vinniefalco Thank you, but I am not looking for a banner, just a logo. Both your banners for Beast and Json are very catchy, it is not my personal style though.

**Comment by eduardo-rodrigues** [comment]
Thanks @HDembinski, I agree with your comments. Let's see what is manageable … Looking forward to it.

**Comment by HDembinski** [comment]
Another version with "H" replacing the letter
![boost_histogram_logo](https://user-images.githubusercontent.com/2631586/67523060-2a8ae980-f6ae-11e9-89c8-79e491ffca66.png)

**Comment by HDembinski** [comment]
@eduardo-rodrigues I tried to add some speed blur, but it just looked blurry when scaled down. So less is more, it seems.

**Comment by eduardo-rodrigues** [comment]
I understand. Worth giving it a try, right?

I quite like this new logo, actually. As one would say in French, it is sober.

**Comment by HDembinski** [comment]
Thanks! Let's see whether there are new comments. I think the latest version is a finalist.

**Comment by henryiii** [comment]
Here's a mockup of what I'm thinking for the Python version:

![BoostHistogramPython](https://user-images.githubusercontent.com/4616906/67574350-43c08400-f708-11e9-8837-cd8904573ff6.png)

**Comment by HDembinski** [comment]
I like it! I would prefer a more stylized snake, but that is a pretty recognizable python! Impressive

**Comment by HDembinski** [comment]
The black/white with the sharp contrast also looks really good.

**Comment by HDembinski** [comment]
Do you insist on having b/w? Otherwise the red of the "Boost" could fade over into green of the python, which would be pretty cool.

**Comment by henryiii** [comment]
The colors should be fairly simple with a clear outline - but a *few* of the Scikit-HEP logos are two-tone, including one or two I've designed. Most importantly, it should look good when the colors are removed.

**Comment by HDembinski** [comment]
The current design is three-tone. If you want to not add more colors, how about making "Boost" including the snake Python-green?

> Most importantly, it should look good when the colors are removed.

Why?

**Comment by eduardo-rodrigues** [comment]
Cute logo, @henryiii.

**Comment by henryiii** [comment]
![BoostHistogramPython](https://user-images.githubusercontent.com/4616906/67577142-e8919000-f70d-11e9-9fe2-eea4c229a6d0.png)

Because then it works as a small outline, it can be themed into a presentation, and because most/all the other Scikit-HEP logos are designed that way, so it looks consistent when shown on a grid page with all the other Scikit-HEP projects. It also has a more modern look.

(Note: This doesn't actually mean we can't make the python green or that we have to be two-tone, I can try that - it just means the logo should also look good monochrome)

**Comment by henryiii** [comment]
![BoostHistogramPythonGrad](https://user-images.githubusercontent.com/4616906/67577919-673afd00-f70f-11e9-8faf-ae07772927b6.png)

I still like the simplicity of fewer colors, either 1 or 2, but here's the multicolor one.

**Comment by henryiii** [comment]
PS: Inkscape 1.0 beta 1 is great, works beautifully on a Mac, fully integrated, finally! (Except for crashing once. But it saved the data and Inkscape always crashed once in a while. )

**Comment by henryiii** [comment]
PS: I also tried a lower case b and h version, we've been calling this `boost-histogram` in Python, but it looked awful. At least the H did.

**Comment by eduardo-rodrigues** [comment]
Agreed that one should not abuse colours, but I rather like the head turning green-ish, as above. Nice work, @henryiii.

**Comment by HDembinski** [comment]
(As Jim would say, try to make shrink it to 50 px and see if it still looks good).

**Comment by eduardo-rodrigues** [comment]
> I like the color change version much better than I thought I would. I'd be okay with that one if others like it.

If I can count, I vote for the 3-colour version with the green head and red tongue.

**Comment by henryiii** [comment]
A bigger head, also playing with the tail a bit:

![BoostHistogramPythonGrad2](https://user-images.githubusercontent.com/4616906/67587440-e0435000-f721-11e9-8958-8cf746296a64.png)

**Comment by HDembinski** [comment]
My wife said that the tail is too playful. I think the bigger head is a plus, it looks much better when scaled down. What bothers me still is the white gap between the "t" and the head. I am not sure what exactly to do about it. I understand that you want the head to be aligned with the end of the "m", but I think it would look more balanced if the head was closer to the "t" or if the white void was filled with something, perhaps a wiggle of the snakes body. That may look too complex then, but the official Python logo also has a very wiggly snake.

**Comment by HDembinski** [comment]
@henryiii If you send me the SVG for the original Black/White version of the Logo, I would like to include that into the boost::histogram repo. I think it would be great to offer a coloured logo and a b/w version. If you have one without the snake, even better. Otherwise I would cut the snake for C++ boost::histogram.

**Comment by henryiii** [comment]
Sure, I can. Everything is in layers, so you can just turn off the snake. (Colors have to be set manually to black, though).

Here's an adjusted snake.

![BoostHistogramPythonGrad3](https://user-images.githubusercontent.com/4616906/67593730-d70daf80-f730-11e9-9082-ce2156a8a416.png)

**Comment by henryiii** [comment]
What happened to the font in the one now posted?

**Comment by HDembinski** [comment]
Apparently, the font is not stored in the SVG. If you don't have the Denmark font installed, it is displayed incorrectly. Will be fixed.
