### ISSUE TITLE
broken EOL in doc/concepts.qbk

### ISSUE THREAD

**Issue by sfindeisen** [boostorg/histogram#204]
I am trying to install modularized Boost on my GNU/Linux by following [these instructions](https://github.com/boostorg/boost/wiki/Getting-Started). I do `git clone`, but then git reports modifications to `doc/concepts.qbk` file in this lib due to automatic EOL conversions.

This is especially annoying when trying to check out Boost as a git submodule (because of uncommited changes propagating upwards).

**Comment by HDembinski** [comment]
Thank you for reporting this. If I understand correctly, you want me to change the EOL characters in this file so git doesn't do automatic conversion, right? If you already know what needs to be done, feel free to submit a PR. Otherwise I will have to look into this.

**Comment by HDembinski** [comment]
Just to check, you did this: `git config --global core.autocrlf true`, right?

**Comment by HDembinski** [comment]
@mloskot Do you have an idea how I could fix this? OP is not responding.

**Comment by mloskot** [comment]
@hdembinski I don't think the OP set autocrlf true on Linux. It would be unusual.

Any chance this case applies to your file? https://stackoverflow.com/a/39078611

I'm travelling this week, having patchy Internet access and mostly on phone, hard to dig it deeper.
