### ISSUE TITLE
FEATURE REQUEST: Add empty

### ISSUE THREAD

**Issue by henryiii** [boostorg/histogram#241]
I would like an `empty(coverage)` function or method for histograms, something like this:

```cpp
bh::empty(hist, bh::coverage::all);
// OR
hist. empty(bh::coverage::all);
```

It could look something like this:

```cpp
template<class histogram_t>
bool empty(const histogram_t &h, bh::coverage cov) {
    using value_type = typename histogram_t::value_type;
    value_type zero = value_type();
    for(auto&& ind : bh::indexed(h, cov)) {
        if(*ind != zero) {
            return false;
        }
    }
    return true;
}
```

This should be faster than sum if the histogram is filled, and would be useful for checking to see if an item fell into the histogram (inner), or for checking to see if this was filled yet (all).

**Comment by HDembinski** [comment]
Sorry, but I think this is not good to have in boost::histogram, because the expectation in C++ is that `.empty()` is a fast O(1) operation. Here it is a very slow operation. The style of the stdlib is to not offer methods at all which have bad performance. Think of std::vector, which does not have `push_front`.

**Comment by HDembinski** [comment]
Ah wait, on second glance, this is a free function not a method, so it would not create the conflict in expectation that I was mentioning. Yes, we can definitely have that as a free function.

**Comment by HDembinski** [comment]
If you want to add it, be my guest, but I can also do it.

**Comment by henryiii** [comment]
Okay, I'll add it in a PR in a day or two then you can improve it. :)
