### ISSUE TITLE
Creating category axis from empty sequence disallowed even if growth=true

### ISSUE THREAD

**Issue by henryiii** [boostorg/histogram#252]
Currently, the check for bins does not take into account growth; this makes it impossible to create an empty category axis, for example. The check maybe should look like this instead:

```cpp
if (size() == 0 && !options_type::test(option::growth))
    BOOST_THROW_EXCEPTION(std::invalid_argument("bins > 0 required unless growth is enabled"));
```

(Verified to work in a simple case)

**Comment by HDembinski** [comment]
It is possible to create an empty category axis, just use the default ctor, see axis_category_test.cpp:121.

Nevertheless, passing an empty sequence should be allowed, too, when growth is on, good catch.

**Comment by henryiii** [comment]
It's not possible to make an empty category axis with metadata, then, unless the metadata is set later.

**Comment by HDembinski** [comment]
See https://github.com/HDembinski/histogram/pull/81

**Comment by HDembinski** [comment]
fixed in develop
