### ISSUE TITLE
Flowless histograms unslicable

### ISSUE THREAD

**Issue by henryiii** [boostorg/histogram#257]
You currently cannot slice an axes that has flow bins turned off:

```cpp
using namespace boost::histogram;

auto h = make_histogram(
    axis::integer<int, use_default, axis::option::none_t>(0, 10)
);

auto h1 = algorithm::reduce(h, algorithm::slice(3,6));
```

```
terminate called after throwing an instance of 'boost::wrapexcept<std::out_of_range>'
  what():  at least one index out of bounds
```

(Seen on wandbox with 1.71 and in Python boost-histogram current develop).

**Comment by HDembinski** [comment]
Huh, that is very strange, thanks for reporting the bug.

**Comment by HDembinski** [comment]
Turns out reduce does not work for any axis without underflow/overflow. I am working on a fix.

**Comment by HDembinski** [comment]
Fixed in develop

**Comment by henryiii** [comment]
Works, thank you for the fast fix!

**Comment by HDembinski** [comment]
Thank you for reporting this nasty bug. At least it failed instead of giving a wrong result...
