### ISSUE TITLE
Fail to run check_odr_test.py with boost release package

### ISSUE THREAD

**Issue by yuxianch** [boostorg/histogram#276]
Test check_odr_test.py is trying to check header files of histogram. In this test, the path of header files is defined as below:
`include_path = os.path.join(this_path, "..", "include")`
This works for this github project, but for the boost package provided in [boost.org](https://www.boost.org/users/history/version_1_72_0.html), the path of header files is changed and there are also many other header files. This differences make this test failed when we're using boost package.
I think this test should be updated to fit for this project and also boost package. What do you think?

**Comment by HDembinski** [comment]
Thank you for reporting this bug, you are right of course. I think I can fix this by restricting the test to headers in the histogram subfolder.

**Comment by HDembinski** [comment]
Fixed in master
