### ISSUE TITLE
[bug] weighted_mean variance calculation in +=

### ISSUE THREAD

**Issue by henryiii** [boostorg/histogram#310]
The same issue fixed in #308 with `mean` seems to be present in `weighted_mean`, as well:

```cpp
#include <boost/histogram.hpp>
#include <boost/histogram/accumulators/ostream.hpp>
#include <iostream>

int main() {
  namespace bh = boost::histogram;

  bh::accumulators::weighted_mean a, b, c;
  a(1); a(2); a(3);
  
  b(5); b(6);
  
  c(1); c(2); c(3); c(5); c(6);
  
  auto d = a;
  d += b;
  
  std::cout << d << " " << c << " " << (a == b ? "Same" : "Different") << std::endl;
}
```

```
weighted_mean(5, 3.4, 0.625) weighted_mean(5, 3.4, 4.3) Different
```

**Comment by henryiii** [comment]
Why is `weighted_mean& operator*` not noexcept?

**Comment by henryiii** [comment]
Exaclty the same fix fixes WeighedMean. I've fixed it in https://github.com/scikit-hep/boost-histogram/pull/537 - I can apply the same fix here if you'd like, @HDembinski, or you can do it, whatever you think is faster/easier to get in.

**Comment by HDembinski** [comment]
I suspected as much, but planned to implement this later.

**Comment by HDembinski** [comment]
Taken care of in #308 also the missing noexcept that you found.
