### ISSUE TITLE
Bin count is limited by `unsigned`

### ISSUE THREAD

**Issue by vakokako** [boostorg/histogram#332]
`histogram::axis::regular` constructor takes bins count as `unsigned`. Are there any plans to support bigger types?

There is `histogram::axis::index_type`, maybe adding equivalent for bin count so that this could be a simple patch if somebody would want lets say `size_t` number of bins.

**Comment by henryiii** [comment]
Just curious, do you have an actual use case for more than four billion bins in a single histogram axis?

**Comment by HDembinski** [comment]
What @henryiii said. 
`unsigned` is deemed large enough (by a huge margin) and so there are currently no plans to support a bigger type per axis, but if you have a convincing use-case, I am happy to consider this.

**Comment by HDembinski** [comment]
Note that a multi-dimensional histogram is allowed to have more four billion bins. The restriction here is four billion bins **per axis**.

**Comment by vakokako** [comment]
It's true, the number of bins is probably enough. It's mostly for consistency with most other containers, where the `size_t` is used for size.
